version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: bridge

  feedapp:
    build:
      context: .
    container_name: feedapp
    ports:
      - "8080:8080"
    environment:
      - TZ = Europe/Oslo
    depends_on:
      - rabbitmq
    env_file:
      - .env
    network_mode: bridge

  frontend:
    build:
      context: ../frontend/feedapp-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - TZ = Europe/Oslo
    #volumes:
      #- /etc/localtime:/etc/localtime:ro
    network_mode: bridge
